set(AVL_TEST_LIST
    ${PROJECT_SOURCE_DIR}/tests/basic.random_insert_remove.cpp
    ${PROJECT_SOURCE_DIR}/tests/iterators.dereference.cpp
    ${PROJECT_SOURCE_DIR}/tests/iterators.ordering.cpp
    ${PROJECT_SOURCE_DIR}/tests/tree.clear.cpp
    ${PROJECT_SOURCE_DIR}/tests/tree.copy_assign.cpp
    ${PROJECT_SOURCE_DIR}/tests/tree.copy.cpp
    ${PROJECT_SOURCE_DIR}/tests/tree.equality.cpp
    ${PROJECT_SOURCE_DIR}/tests/tree.move_assign.cpp
)
